name: 'flyte-serialyze'
description: 'serialyze-workflows'
inputs:
  config:  # id of input
    description: 'config for the project'
    required: true
  tag:  # id of input
    description: 'tag'
    required: true
  requirements:
    description: 'requirements'
    required: true
outputs:
  outputs: # id of output
    description: 'outputs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config }}
    - ${{ inputs.tag }}
    - ${{ inputs.requirements }}